export const DummyRank = [
    {
        Rank: "01",
        Collection: "Dancing Banana",
        volumn: "133.43 ETH",
        Change: "-48.31%",
        FloorPrice: "133 ETH",
        Owners: "3.2K",
        Graph: "-48.31%",
        NFTs: "10.0K",
    },
    {
        Rank: "02",
        Collection: "Dancing Banana",
        volumn: "133.43 ETH",
        Change: "-48.31%",
        FloorPrice: "133 ETH",
        Owners: "3.2K",
        Graph: "-48.31%",
        NFTs: "10.0K",
    },
    {
        Rank: "03",
        Collection: "Dancing Banana",
        volumn: "133.43 ETH",
        Change: "-48.31%",
        FloorPrice: "133 ETH",
        Owners: "3.2K",
        Graph: "-48.31%",
        NFTs: "10.0K",
    },
    {
        Rank: "04",
        Collection: "Dancing Banana",
        volumn: "133.43 ETH",
        Change: "-48.31%",
        FloorPrice: "133 ETH",
        Owners: "3.2K",
        Graph: "-48.31%",
        NFTs: "10.0K",
    },
    {
        Rank: "05",
        Collection: "Dancing Banana",
        volumn: "133.43 ETH",
        Change: "-48.31%",
        FloorPrice: "133 ETH",
        Owners: "3.2K",
        Graph: "-48.31%",
        NFTs: "10.0K",
    },
    {
        Rank: "06",
        Collection: "Dancing Banana",
        volumn: "133.43 ETH",
        Change: "-48.31%",
        FloorPrice: "133 ETH",
        Owners: "3.2K",
        Graph: "-48.31%",
        NFTs: "10.0K",
    },
    {
        Rank: "07",
        Collection: "Dancing Banana",
        volumn: "133.43 ETH",
        Change: "-48.31%",
        FloorPrice: "133 ETH",
        Owners: "3.2K",
        Graph: "-48.31%",
        NFTs: "10.0K",
    },
    {
        Rank: "08",
        Collection: "Dancing Banana",
        volumn: "133.43 ETH",
        Change: "-48.31%",
        FloorPrice: "133 ETH",
        Owners: "3.2K",
        Graph: "-48.31%",
        NFTs: "10.0K",
    },
    {
        Rank: "09",
        Collection: "Dancing Banana",
        volumn: "133.43 ETH",
        Change: "-48.31%",
        FloorPrice: "133 ETH",
        Owners: "3.2K",
        Graph: "-48.31%",
        NFTs: "10.0K",
    },
    {
        Rank: "10",
        Collection: "Dancing Banana",
        volumn: "133.43 ETH",
        Change: "-48.31%",
        FloorPrice: "133 ETH",
        Owners: "3.2K",
        Graph: "-48.31%",
        NFTs: "10.0K",
    },
    {
        Rank: "11",
        Collection: "Dancing Banana",
        volumn: "133.43 ETH",
        Change: "-48.31%",
        FloorPrice: "133 ETH",
        Owners: "3.2K",
        Graph: "-48.31%",
        NFTs: "10.0K",
    },

];